### ISSUE TITLE
 音视频推送、纯音频推送、纯视频推送

### ISSUE THREAD

**Issue by douya40** [EasyDarwin/EasyPusher-Android#21]
功能介绍的这一条具体怎么实现

**Comment by douya40** [comment]
这个产品有人维护吗，没有话，早点下架，提个问都没人回答

**Comment by milkywayriver** [comment]
![image](https://user-images.githubusercontent.com/4143638/47251823-23fade00-d46c-11e8-8eae-d5053ad8d372.png)
