### ISSUE TITLE
音频的怎么控制麦克风的关和开

### ISSUE THREAD

**Issue by douya40** [EasyDarwin/EasyPusher-Android#27]
音频的怎么控制麦克风的关和开

**Comment by milkywayriver** [comment]
在设置里面选“仅推送视频”即可关闭音频

**Comment by gfm688** [comment]
选“推送音视频” 正常
选“仅推送视频”播放时视频卡住不动
不知怎么回事

void setMediaInfo(int videoCodec, int videoFPS, int audioCodec, int audioChannel, int audioSamplerate, int audioBitPerSample);

既然关闭音频了，理论上setMediaInfo 就不需要设置音频编码等音频信息了

**Comment by gfm688** [comment]
> 在设置里面选“仅推送视频”即可关闭音频

但我测试结果是这样的：
选“推送音视频” 正常
选“仅推送视频” 播放时视频卡住不动

void setMediaInfo(int videoCodec, int videoFPS, int audioCodec, int audioChannel, int audioSamplerate, int audioBitPerSample);
既然关闭音频了，理论上setMediaInfo 就不需要设置音频编码等音频信息了
