### ISSUE TITLE
无法对焦

### ISSUE THREAD

**Issue by UniEa** [EasyDarwin/EasyPusher-Android#29]
无法对焦，在安卓5.0和8.0真机上都是这样

**Comment by UniEa** [comment]
try {
                mCamera.autoFocus(null);
            } catch (Exception e) {
                //忽略异常
                Log.i(TAG, "auto foucus fail");
            }

将autoFocus注释掉后可以正常对焦

**Comment by milkywayriver** [comment]
是的。已改过 谢谢
