### ISSUE TITLE
有办法跳过RTSP协商直接调用RTP协议发送流数据么?

### ISSUE THREAD

**Issue by lazyxwq** [EasyDarwin/EasyPusher-Android#32]
你好,
    我目前有一个工程，用的sip协议控制rtp推流，我如果想要使用这个pusher的库的话是不是没法使用？我看到
mEasyPusher.start(ip, port, String.format("%s.sdp", id), Pusher.TransType.EASY_RTP_OVER_TCP);
这里应该是直接集成了rtsp的控制逻辑，外加rtp发送数据的逻辑。
想请问一下有没有其他API可以直接启动rtp往指定的IP和PORT上发送rtp数据包？

谢谢

**Comment by hxzcan** [comment]
哥们，解决了吗

**Comment by hxzcan** [comment]
> 你好,
> 我目前有一个工程，用的sip协议控制rtp推流，我如果想要使用这个pusher的库的话是不是没法使用？我看到
> mEasyPusher.start(ip, port, String.format("%s.sdp", id), Pusher.TransType.EASY_RTP_OVER_TCP);
> 这里应该是直接集成了rtsp的控制逻辑，外加rtp发送数据的逻辑。
> 想请问一下有没有其他API可以直接启动rtp往指定的IP和PORT上发送rtp数据包？
> 
> 谢谢



> 你好,
> 我目前有一个工程，用的sip协议控制rtp推流，我如果想要使用这个pusher的库的话是不是没法使用？我看到
> mEasyPusher.start(ip, port, String.format("%s.sdp", id), Pusher.TransType.EASY_RTP_OVER_TCP);
> 这里应该是直接集成了rtsp的控制逻辑，外加rtp发送数据的逻辑。
> 想请问一下有没有其他API可以直接启动rtp往指定的IP和PORT上发送rtp数据包？
> 
> 谢谢

哥们，解决了吗？你是怎么做的

**Comment by 953113003** [comment]
解决了，替换了sdk文件




------------------ 原始邮件 ------------------
发件人: "hxzcan"<notifications@github.com>;
发送时间: 2019年10月23日(星期三) 下午2:58
收件人: "EasyDarwin/EasyPusher-Android"<EasyPusher-Android@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [EasyDarwin/EasyPusher-Android] 有办法跳过RTSP协商直接调用RTP协议发送流数据么? (#32)




哥们，解决了吗

**Comment by 953113003** [comment]
没做过rtp，我也不清楚




------------------ 原始邮件 ------------------
发件人: "hxzcan"<notifications@github.com>;
发送时间: 2019年10月23日(星期三) 下午2:59
收件人: "EasyDarwin/EasyPusher-Android"<EasyPusher-Android@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [EasyDarwin/EasyPusher-Android] 有办法跳过RTSP协商直接调用RTP协议发送流数据么? (#32)



 
你好,
 我目前有一个工程，用的sip协议控制rtp推流，我如果想要使用这个pusher的库的话是不是没法使用？我看到
 mEasyPusher.start(ip, port, String.format("%s.sdp", id), Pusher.TransType.EASY_RTP_OVER_TCP);
 这里应该是直接集成了rtsp的控制逻辑，外加rtp发送数据的逻辑。
 想请问一下有没有其他API可以直接启动rtp往指定的IP和PORT上发送rtp数据包？
 
谢谢
   
你好,
 我目前有一个工程，用的sip协议控制rtp推流，我如果想要使用这个pusher的库的话是不是没法使用？我看到
 mEasyPusher.start(ip, port, String.format("%s.sdp", id), Pusher.TransType.EASY_RTP_OVER_TCP);
 这里应该是直接集成了rtsp的控制逻辑，外加rtp发送数据的逻辑。
 想请问一下有没有其他API可以直接启动rtp往指定的IP和PORT上发送rtp数据包？
 
谢谢
  
哥们，解决了吗？你是怎么做的

**Comment by hxzcan** [comment]
替换了什么SDK,方便告诉下怎么使用吗，使用rtp来推流吗？



------------------ 原始邮件 ------------------
发件人: "YangKai"<notifications@github.com>; 
发送时间: 2019年10月23日(星期三) 下午2:59
收件人: "EasyDarwin/EasyPusher-Android"<EasyPusher-Android@noreply.github.com>; 
抄送: "362970502"<362970502@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [EasyDarwin/EasyPusher-Android] 有办法跳过RTSP协商直接调用RTP协议发送流数据么? (#32)



解决了，替换了sdk文件 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "hxzcan"<notifications@github.com>; 
 发送时间: 2019年10月23日(星期三) 下午2:58 
 收件人: "EasyDarwin/EasyPusher-Android"<EasyPusher-Android@noreply.github.com>; 
 抄送: "Subscribed"<subscribed@noreply.github.com>; 
 主题: Re: [EasyDarwin/EasyPusher-Android] 有办法跳过RTSP协商直接调用RTP协议发送流数据么? (#32) 
 
 
 
 
 哥们，解决了吗

**Comment by lazyxwq** [comment]
看起来用这个库是没办法解决的，我后面没有用这个库了。
