### ISSUE TITLE
txtOverlay水印问题

### ISSUE THREAD

**Issue by iQuick** [EasyDarwin/EasyPusher-Android#37]
txtOverlay水印的文字大小可以调吗？

**Comment by leo-09** [comment]
可以，加我微信18855117272------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;小步哥&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年5月28日(星期四) 下午5:26
收件人:&nbsp;&quot;EasyDarwin/EasyPusher-Android&quot;<EasyPusher-Android@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[EasyDarwin/EasyPusher-Android] txtOverlay水印问题 (#37)
